name = "ParametricAirfoils"
uuid = "4c14af30-da9f-11e9-34cd-f9f0aee9fd2c"
authors = ["Cheng Xue <xuecheng@nuaa.edu.cn>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
